### ISSUE TITLE
TODO Roadmap

### ISSUE THREAD

**Issue by jeffgodwyll** [GDGGhana/devfest-2017#1]
### Fix Config
 - [x] Mailchimp setup
 - [x] link to firebase project - https://console.firebase.google.com/u/2/project/devfest-gh/overview
 - [ ] load initial firebase schema
 - [ ] Google events page
 - [ ] Google events album
 - [ ] Youtube sessions url (more like playlist for speaker talks
 - [x] start and end dates for devfest
 - [x] meetup location (name, lat and long)
 - [x] background images

 ### Fix resources json
 - [ ] fix all gdg ghana specific text
 - [x] correct footer block urls
 - [ ] contact block
 - [ ] media kit urls
 - [ ] call to action video id

### FIx blog json
 - [ ] ~~link to all blog posts~~

## Images Folder

 - [ ] backgrounds
 - [x] favicon, logos
 - [ ] people
 - [ ] sessions, posts etc

## Index File

 - [ ] customise more
 - [x] setup google analytics
 - [ ] custom styling

## CI Setup
 - [x] set up travis
 - [x] link to firebase
 - [x] push to deploy

**Comment by jeffgodwyll** [comment]
Test
